### ISSUE TITLE
Auth mechanism change

### ISSUE THREAD

**Issue by patricktokeeffe** [mtanda/grafana-google-calendar-datasource#19]
This plugin is a great idea, thanks for putting it together. 👍 I've gotten it working where both Grafana and I use the same Google account, and where Grafana uses an account A for API access (client ID) while I use a second account B to add the calendar (calendar ID). 

The requirement to stay logged into the Google account to view the annotations is a problem for us, though. It means other Grafana users can view the dashboards, but not the annotations. Also, I cannot display on a public kiosk without leaving the kiosk logged into the calendar owner's Google account. I was not able to fix user calendar access by granting sharing permissions or making the calendar public - only the calendar owner could load the annotations. 

Would it be possible to use a different integration method? i.e. the "*Secret address in iCal format*" uri which is always available despite sharing settings:

![image](https://user-images.githubusercontent.com/1348834/64195888-697f8a00-ce37-11e9-9782-54844446973c.png)

**Comment by mtanda** [comment]
Thanks for proposing improvement idea.
I'll try it.

**Comment by mtanda** [comment]
I think the feature is out of scope.
Because the dataformat is iCal, it doesn't use Google Calendar API.
So, it is better to create another Grafana datasource plugin, "iCal datasource".

It is easy to create datasource, so I recommend to create plugin by using `ical.js`.
https://github.com/mozilla-comm/ical.js/

**Comment by patricktokeeffe** [comment]
> Because the dataformat is iCal, it doesn't use Google Calendar API.
So, it is better to create another Grafana datasource plugin, "iCal datasource".

Hi @mtanda thanks for looking into it! I also realized (today) this would make it a generic .ical data source, and therefore probably makes more sense as different plugin.  :+1:
