### ISSUE TITLE
Fix/update images in README

### ISSUE THREAD

**Issue by anatoly-yakubov-betpawa** [mtanda/grafana-google-calendar-datasource#21]
Links to two images listed in README are broken:
https://raw.githubusercontent.com/mtanda/grafana-google-calendar-datasource/master/dist/images/annotation_config.png
https://raw.githubusercontent.com/mtanda/grafana-google-calendar-datasource/master/dist/images/calendar.png

**Comment by mtanda** [comment]
Thanks for notice. Fixed it!
