### ISSUE TITLE
Scrape public calendars

### ISSUE THREAD

**Issue by jeffeb3** [mtanda/grafana-google-calendar-datasource#28]
Is it possible to create a public calendar and then use this plugin to read the calendar without giving it access to my google account? My google account is the key to my whole digital life and I'd rather not authorize my pi to use it.

I may be being paranoid, but I'd really like to just put my kid's school schedule in a public list, and then display it in grafana.

BTW, I am getting straight to the point, but I do appreciate the work you've done and I appreciate that open source software is a community effort, not something where I can just demand features I want :). There's probably a simple solution I'm just not finding.

Thank you.

**Comment by mtanda** [comment]
This datasource use Google Calendar API to scrape schedule, and doesn't support public calendar.

I didn't try, but Google Calendar seems to support exporting calendar as iCal format.
https://support.google.com/calendar/answer/37648?hl=en

If you want to display public calendar, create new datasource for iCal format.
Creating datasource is not so difficult (if you have experience JavaScript), essential part of datasource is `annotationQuery()`.
https://github.com/mtanda/grafana-google-calendar-datasource/blob/1.0.8/src/datasource.ts#L265-L316

please read related comment.
https://github.com/mtanda/grafana-google-calendar-datasource/issues/19#issuecomment-528305307

**Comment by mtanda** [comment]
Most easiest way is using https://github.com/grafana/simple-json-datasource, and converting iCal to simple-json-datasource format.

**Comment by jeffeb3** [comment]
I was also looking into the magic mirror project and they do use the ical format in one of the default calendar (event) widget:

https://github.com/MichMich/MagicMirror/blob/master/modules/default/calendar/calendarfetcher.js

That project is MIT, so I suppose a datasource based on that fetcher and producing events wouldn't be so much work. I'll have to take a look.

**Comment by jeffeb3** [comment]
To be clear, Thank you for thinking about this. Not including ical in this plugin is totally reasonable. I don't mind at all that you've said it's out of scope.

**Comment by mtanda** [comment]
Thanks for sharing your work :-)

It is good hint, if another one want to show iCal calendar on Grafana.
I close this issue.
