### ISSUE TITLE
Annotation Query Failed

### ISSUE THREAD

**Issue by micheljung** [mtanda/grafana-google-calendar-datasource#7]
I followed the steps and added an annotation to the calendar `faforever.com_cpellm2p2sdfr8dfmnmgs1davk@group.calendar.google.com`.

Upon clicking "Save", I get "Cannot read property 'length' of undefined".

Grafana v4.5.1
Plugin v1.0.2

**Comment by ThomasADavis** [comment]
Quota for the api is blown.

{
"error": {
"errors": [
{
"domain": "usageLimits",
"reason": "dailyLimitExceededUnreg",
"message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
"extendedHelp": "https://code.google.com/apis/console"
}
],
"code": 403,
"message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
}
}

**Comment by ThomasADavis** [comment]
hmm.. that may not be it either..

looking..

**Comment by ThomasADavis** [comment]
I know what is happening, but not sure how to fix it.

The code is not returning an array from the calendar, it's returning the auth token.  There is an initilization call that is series of promises, the gapi.client.event.calender.list appears to be running async..  so the init is returning the wrong thing.

Still looking at it..

**Comment by mtanda** [comment]
Sorry, it's bug of plugin. Will fix in this version.
https://github.com/grafana/grafana-plugin-repository/pull/186

**Comment by micheljung** [comment]
I just updated it to 1.0.4, but now it displays:

```

Annotation Query Failed
{"result":{"error":{"errors":[{"domain":"global","reason":"notFound","message":"Not Found"}],"code":404,"message":"Not Found"}},"body":"{\n \"error\": {\n \"errors\": [\n {\n \"domain\": \"global\",\n \"reason\": \"notFound\",\n \"message\": \"Not Found\"\n }\n ],\n \"code\": 404,\n \"message\": \"Not Found\"\n }\n}\n","headers":{"date":"Fri, 08 Dec 2017 22:22:54 GMT","content-encoding":"gzip","server":"GSE","content-type":"application/json; charset=UTF-8","vary":"Origin, X-Origin","cache-control":"private, max-age=0","content-length":"120","expires":"Fri, 08 Dec 2017 22:22:54 GMT"},"status":404,"statusText":null}
```

Not sure what it's telling me and where it comes from

**Comment by ThomasADavis** [comment]
Make sure you clear your browser cache or do a force reload (shift-reload button on Chrome)

**Comment by micheljung** [comment]
I did, also used incognito mode as well as different browser, same issue.
