### ISSUE TITLE
problems connecting to google..

### ISSUE THREAD

**Issue by ThomasADavis** [mtanda/grafana-google-calendar-datasource#8]
The latest git version (1.0.2), Grafana 4.6.0.  oauth keys are correct, I have several other projects doing this..

From the console:

details: "Not a valid origin for the client: https://grafana has not been whitelisted for client ID 
xxxxxxxx.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID."

with the error of:

error: idpiframe_initialization_failed

using google chrome

on firefox, I get the same error.  I am logged in on gmail, with the correct account on both browsers.

**Comment by micheljung** [comment]
This isn't an issue of this plugin. The error message tells you exactly what to do; go to the google console and add https://grafana to the whitelist.

**Comment by ThomasADavis** [comment]
Ok, figured it out - picked the wrong thing 'other', not web source.

getting further, but now I get this:

AnnotationSrv.query error TypeError: Cannot read property 'length' of undefined
    at t.translateQueryResult (annotations_srv.ts:179)
    at annotations_srv.ts:141
    at u (angular.js:17051)
    at angular.js:17095
    at f.$digest (angular.js:18233)
    at angular.js:18462
    at i (angular.js:6362)
    at angular.js:6642

**Comment by micheljung** [comment]
Welcome to the club :) See #7

**Comment by mtanda** [comment]
Original issue seems to be resolved. So, close this :-)
