### ISSUE TITLE
Feature change

### ISSUE THREAD

**Issue by ThomasADavis** [mtanda/grafana-google-calendar-datasource#9]
When looking at a previous issue, I found we can join the start and end dates together to cover the region.  This makes a better looking annotation in our view.

This change looks like this:

![grafana-gcal](https://user-images.githubusercontent.com/12158973/32672661-bcc434c2-c600-11e7-9ba4-2d4a92499536.jpeg)

I am not sure older grafana versions support this change.  I know 4.6 and newer does.

I've also changed the tags to show that the annotation is from google calender, and which google calender the annotation came from; try it with 3 or 4 different google calendars.. you'll appreciate the change.

Also, if the event.description is empty (we have a few calenders this way), you'll get None in the text field. it should be just blank.

I am also submitting a pull request to do this.

**Comment by mtanda** [comment]
PR is merged :)
